version: '3.9'
services:
  app:
    # Comment the line below if you don't want to use the `hybrid/latest` image.
    # image: neonmmd/websurfx:latest
    # Uncomment the line below if you want to use the `no cache` image.
    # image: neonmmd/websurfx:nocache
    # Uncomment the line below if you want to use the `memory` image.
    image: neonmmd/websurfx:memory
    ports:
      - 8080:8080
    # Uncomment the following lines if you are using the `hybrid/latest` or `redis` image.
    # depends_on:
    #   - redis
    # links:
    #   - redis
    volumes:
      - ./websurfx/:/etc/xdg/websurfx/
  # Uncomment the following lines if you are using the `hybrid/latest` or `redis` image.
  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  builder:
    build: .
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    push: true
    secrets:
      - name: GITHUB_TOKEN
        value: ${{ secrets.GITHUB_TOKEN }}